# See this guide for more settings:
#
# http://about.travis-ci.org/docs/user/build-configuration/

language: clojure
jdk: oraclejdk7
install:
        - export BWD=`pwd`
        
env:
        matrix:
                - NAME=cascalog-core
                - NAME=cascalog-lzo
                - NAME=cascalog-checkpoint
                - NAME=cascalog-math
                - NAME=cascalog-more-taps
                - NAME=midje-cascalog                
script:
        - cd ${BWD}/${NAME}
        - ${BWD}/travis_fix_proj.py project.clj
        - LEIN_SNAPSHOTS_IN_RELEASE=yup lein uberjar                
        - cd ${BWD}
